### ISSUE TITLE
Type property can only contain one value

### ISSUE THREAD

**Issue by ghost** [w3c-ccg/verifiable-conditions#3]
Team Gimly is leading the implementation of the Verifiable Credentials standard as part of the [EOSIO DID](https://github.com/Gimly-Blockchain/eosio-did-resolver/blob/c49d23b3053a174cb78e1b7704f2bd43f9be3ab4/src/resolver.ts#L80). The standard specifies a new verification method type that looks like this:
```json
{
    "id": "did:example:123",
    "controller": "did:example:123",
    "type": ["VerifiableCondition", "VerifiableConditionAnd"],
    "verificationMethod": [...],
}
```

We think there may be a problem with the Verifiable Credentials standard, as the type property does not conform to the [DID-core](https://w3c.github.io/did-core/#verification-methods) spec regarding the type property of verification methods:

> The value of the type property MUST be a string that references exactly one verification method type. In order to maximize global interoperability, the verification method type SHOULD be registered in the DID Specification Registries [DID-SPEC-REGISTRIES].

As such, I propose that the Verifiable Condition is a single type, and that subtypes can be expressed like below. Please let me know what you think!
```
{
    "id": "did:example:123",
    "controller": "did:example:123",
    "type": "VerifiableCondition",
    "conditionType": ["VerifiableConditionAnd"],
    "verificationMethod": [...],
}
```

**Comment by ghost** [comment]
A second proposal by @msporny has arisen to solve this issue

> Fundamentally, you may be modelling the cryptographic conditions in a strange way.

> Jack, have you considered not using type to specify ANDs and ORs and using a
property instead? It's a nuanced but important difference (and forgive me if
you have as I haven't spent as much time thinking about this problem as you
probably have):

> "requireAllConditions": [VM1, VM2, VM3]

> "requireAnyCondition": [VM3, VM4, VM5]

> It feels like you can build all logical variations by then nesting other VMs
inside? I haven't done the work to figure out if this is true and wanted to
check with you before we tried going down that path.

To continue this discussion, please refer to the two strategies as @gimly-jack and @msporny strategies (just a logical way to reference and not meant to imply competition)

**Comment by OR13** [comment]
I recommend not overloading type, its generally good to keep properties focused on doing 1 thing very well.

**Comment by kdenhartog** [comment]
+1 to @msporny approach. The most common thing I've seen is JSON base parsing on the value of the `@type` property. If this is a string or an array it will make the implementation logic much harder. Additionally if the combination of parameters in the Array has an effect on branching logic it will increase the code complexity as well. This could potentially lead to bugs in the implementations which ultimately would produce validation vulnerabilities during authentication processes.

**Comment by ghost** [comment]
I want to summarize two strategies and collect feedback. Notes:
- in all strategies, the "type" property of the verification method has one value "VerifiableCondition2021"
- each verification method of type "VerifiableCondition2021" MAY have ONLY one condition (e.g. And, Or, Thershold)
- each verification method of type "VerifiableCondition2021" MAY have several several relationships as shown below
- each verification method of type "VerifiableCondition2021" MUST have at least one condition or relationship (it cannot be empty

## "Jack's proposal"
```json
{
    "id": "did:example:account1#1",
    "controller": "did:example:account1",
    "type": "VerifiableCondition2021",
    "conditionType": ["And", "Relationship"],
    "verificationMethod": ["#1", "#2"],
    "parentIdUrl": ["did:example:account2#3"],
    "childIdUrl": ["did:example:account1#0"],
}
```
or
```json
{
    "id": "did:example:account1#1",
    "controller": "did:example:account1",
    "type": "VerifiableCondition2021",
    "conditionType": ["WeightedThreshold"],
    "verificationMethod": ["#1", "#2"],
}
```

Pros:
- program needs to read "conditionType" to see what types it will be. it can then check only for the properties indicated in this type

Cons:
- multiple condition types may lead to implementation complexity in handling multiple types (because all this logic must be handled when checking one property "conditionType"

## "Manu's proposal"
```json
{
    "id": "did:example:account1#1",
    "controller": "did:example:account1",
    "type": "VerifiableCondition2021",
    "conditionAnd": ["#1", "#2"],
    "relationshipParentIdUrl": ["did:example:account2#3"],
    "relationshipChildIdUrl": ["did:example:account1#0"],
}
```
or
```json
{
    "id": "did:example:account1#1",
    "controller": "did:example:account1",
    "type": "VerifiableCondition2021",
    "conditionWeightedThreshold": ["#1", "#2"]
}
```

Pros:
- condition types can be determined based on the objects properties, the different logic for each condition type can then be more modular and linked to it's condition type

Cons:
- all potential condition type properties need to be checked to see if it is that type, taking extra time

_________________________________________

I think the 2nd way "Manu's proposal" makes slightly more sense, but don't feel strongly.

Please post any other advantages / disadvantages below and your opinion.

**Comment by ghost** [comment]
@msporny @peacekeeper @OR13 @kdenhartog

**Comment by OR13** [comment]
I like manu's proposal since it does not reuse terms like `verificationMethod`

**Comment by peacekeeper** [comment]
We discussed this today on the [DIF I&D WG call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md), and I also slightly prefer the second option, since it doesn't require the extra "conditionType" array.

**Comment by ghost** [comment]
Thanks. I will go ahead with Manu's and update the spec

**Comment by kdenhartog** [comment]
Just looking at this now. +1 to second proposal. I'm liking the direction things are going here. Thanks for keeping this work moving forward.

**Comment by ghost** [comment]
Updated in PR https://github.com/w3c-ccg/verifiable-conditions/pull/6
